### ISSUE TITLE
Rewrite declaration file to make TypeScript happy

### ISSUE THREAD

**Issue by longnguyen2004** [Yahweasel/libav.js#66] opened 2024-10-21 03:45 UTC
First off, sorry for being one of the people who use this package in Node.js 😅 My use case involves in-process demuxing, and I can't find an up-to-date maintained native Node.js binding for FFmpeg API (not to mention having to build the binding myself when installing). Thus, all of this only makes sense when TypeScript is used in `Node16`/`NodeNext` resolution mode.

Using default exports in a dual ESM/CommonJS package is problematic. Since the `package.json` of this package doesn't have `"type": "module"`, TypeScript assumes this is a CommonJS module, and expects this:
```typescript
let LibAV;
export default LibAV;
```
...to become this
```typescript
module.exports.default = LibAV;
```
which is not what we're doing at all, and breaks downstream usage of the package
```typescript
let LibAV = require("@libav.js/variant-default");
LibAV.LibAV // what we export, but is not what TypeScript expects
LibAV.default.LibAV // what TypeScript expects, but is not what we export
```

Even worse, this also breaks ESM usage of the package in Node, in the same way as above. TypeScript expects the default export to have an extra `default` property.
```typescript
import LibAV from "@libav.js/variant-default";
LibAV.LibAV // what we export, but is not what TypeScript expects
LibAV.default.LibAV // what TypeScript expects, but is not what we export
```

(see [johnloy/esm-commonjs-interop-manual](https://github.com/johnloy/esm-commonjs-interop-manual#white_check_mark--do-prefer-named-exports-when-authoring-a-package-in-esm-targeting-node-or-universal-consumption) for more details)

The easiest way to fix this would be to make `LibAV` a named export (`export default LibAV` -> `export { LibAV }`, `module.exports = LibAV` -> `exports.LibAV = LibAV`). Since this would be an API change, I'm asking for your opinion if we should continue with this approach.

(We can also drop CommonJS support altogether, and make this package ESM-only, which I strongly prefer over the approach above)

**Comment by Yahweasel** [comment] 2024-10-21 11:37
The only support I *really* care about is how it loads in the web browser. For that reason, I'm certainly not going ESM-only, but how exactly the modules work is fungible. The important part is that when loaded in a web browser, it exposes a global variable “LibAV”. Old-school IIFE.

For something like demuxing, I guess using libav.js in Node isn't *utterly* ridiculous (it's not like using a WebCodecs codec when you could use a native one), but I sure wish there was just a more up-to-date native binding of FFmpeg so I didn't need to dip my toes in Nodeland at all. That being said, something that affects the API on Node but not on the web is not, as far as I'm concerned, an API change.

I have a very ossified view of JavaScript and TypeScript, and rarely keep up as things change. Is it possible to both export LibAV as default *and* have `import * as LibAV from "foo"` give us `LibAV.LibAV`, so that nothing old breaks, but default import works?

**Comment by longnguyen2004** [comment] 2024-10-21 13:01
If you don't care much about Node.js, then I suggest dropping the CommonJS stuff out of the pre-ES6 file (`module.exports` and `require`) and treat Node.js as another ES6 platform. Node.js users targeting native ESM will then import the usual way (`import LibAV from "@libav.js/variant-default"`), and people who are stuck on CommonJS for whatever reason can do `const LibAV = await import("@libav.js/variant-default").then(m => m.default)`. ESM support in Node.js has been stable since 5 years ago, so I don't expect the change to cause much breakage.

**Comment by Yahweasel** [comment] 2024-10-21 13:10
You seem to imagine that I put the CommonJS stuff *into* the pre-ES6 file ;) . Emscripten put it there.

**Comment by longnguyen2004** [comment] 2024-10-21 13:29
I...didn't know that 😅 never used any WebAssembly stuff before

Anyway, what I'm basically saying is to remove these
https://github.com/Yahweasel/libav.js/blob/cc3f81371629f5f833383be8ebaf6248aca022a0/libav.in.js#L42
https://github.com/Yahweasel/libav.js/blob/cc3f81371629f5f833383be8ebaf6248aca022a0/libav.in.js#L276-L278
https://github.com/Yahweasel/libav.js/blob/cc3f81371629f5f833383be8ebaf6248aca022a0/libav.in.js#L578-L579

(along with the corresponding changes in test files)

Testing on Node can then be done by running the `mjs` file directly.

**Comment by Yahweasel** [comment] 2024-10-21 13:38
Intuitively I feel like it's possible to make this change in a backwards-compatible way (LibAV.LibAV = LibAV or something), but otherwise, as long as it can be contained to Node, I'm unopposed. The API on Node is “only provided for internal testing”, to quote myself.

**Comment by Yahweasel** [comment] 2024-10-25 02:01
(That commit probably shouldn't have actually closed this)

As I suspected, the default-import issue is easy to fix by just setting `libav.default`. But, I'm still not very satisfied, because the import now doesn't expose any useful types, and that's a more fundamental problem with having a default export in the first place. So, I'm looking at what can be done.

An important thing to note is that while I don't consider the behavior on Node to be especially important or set in stone, bundlers are (annoyingly) important, and tend to mimic Node. So I'm still stuck in certain ways.

**Comment by longnguyen2004** [comment] 2024-10-25 02:57
I agree with out about `exports.default = libav` not being satisfactory. It means we have to do
```typescript
import LibAV from "@libav.js/variant-default";
LibAV.default.LibAV() // huh?
```
just to make TypeScript happy. So instead of this whole ordeal, my PR removes the CommonJS code path, and make Node users use the ESM version, which has properly working default exports.

About bundlers, they should (and popular ones like Vite already do) bundle the ESM version, so I don't think we'll have any problem there.

**Comment by Yahweasel** [comment] 2024-10-25 09:31
That is not correct. In the current state of the repository (with that commit),

```typescript
import LibAV from "@libav.js/whatever";
...
await LibAV.LibAV(); // works as expected
```

All I did was make the CJS behavior comply with the interop manual you gave, while also *not* removing anything that was already there.

The problem is the types:

```typescript
import LibAV1 from "@libav.js/whatever";
import * as LibAV2 from "@libav.js/whatever";
...
let la : LibAV1.LibAV; // Error: Since the default export is an object, not a namespace, it exposes no useful types
let la : LibAV2.LibAV; // Works as expected
la = await LibAV1.LibAV(); // Works as expected
if (something === LibAV1.AVERROR_EOF) // also works as expected
la = await LibAV2.LibAV(); // Doesn't work. LibAV2 only exposes types
if (something === LibAV2.AVERROR_EOF) // also doesn't work.
```

but that problem is strictly in the types file. It has nothing to do with the JavaScript or CJS. And, #67 doesn't fix it (or affect it at all), since it doesn't touch the types.

The problem is that I can't find a way (without a bunch of duplication) to make the default export expose types.

**Comment by longnguyen2004** [comment] 2024-10-25 10:46
I made it work, after a lot more time messing around and researching how other people write declaration files for CJS libraries.
The core of it all is [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) and export assignment (the `export =` syntax, which I can't find any docs for). TL;DR, our type file will look like this

```typescript
declare namespace LibAVModule {
    export interface LibAVStatic {
        // a bunch of static
    }
    export interface LibAVOpts {
        // options to the factory function
    }
    export interface LibAVWrapper extends LibAVOpts, LibAVStatic {
        LibAV(opts: LibAVOpts): Promise<...>;
        // the rest of the overloads here
    }
}
declare const LibAVModule: LibAVModule.LibAVWrapper;
export = LibAVModule;
```

By naming both the namespace and the exported object the same (`LibAVModule` in this case), TypeScript will merge the types of the two together, allowing us to export both of them under a single name. The `export =` syntax prevents TypeScript from generating the hacky `default` property.

The result of it can be seen [here](https://www.typescriptlang.org/dev/bug-workbench/?module=5#code/PTAEAEFsHsBMFcA2BTAXKZBnAbAKBBAGYCWKAdgIaRqgUB0sdALprrMgMaIUBOyolapgAOFDvwAyxAEYBBAGoBZOEn4BvXKC0YAHsOg8moYmSbIehMZJkKAykwpNiHUBu3vj2ACxNohbwAUiNDoZPCQ0uYANKAAFsSh4ZE8AJSJEeYA3JoeWv4+0MSBAG4UiOnJaaAA2mEZPDF1yQC62blaRV4AKtAAQsQA5gCSpkEhAknRcQkT9VX9w6bIA1k5udKDI0w9nQGl5aALW8vmVbWTDbMt2WseCgD6APIACl33tgCisgBKAMIAEvcAUMJAARb4fAByFVW7VACkUH1BQ1k9y6AE1nh97gBVSEAaUhjwA6tCrrD2gikSi0ZjsfIhqCPo8YTw2pSlNTURisfdZDjkSzyWzbu4qcjuXT7qDZF1ZKz2blxTSedjbDjel0hl0JB8FaLtMrJbzZXKAYjIV19XCHrZZIpnrr7gAxRRvImQvXCxV3eTve2O7Gut44gAc1o5-odTuD7wAjNgI0q-Xbo0G3e8AMwAJiTvqjgZdGedEit3oNWltAZjGdBvQkebFKer6ZDoeejcNzbTRbetgTHfLNu7hdjthzg6aFOTBZrbxLXUnFx9Tdnrel9aX9RXXbXvfe3k7lZHc4PXi3yR3x73schvSP8L9zyGAA19x6vVORcP7s+37H0RxeQvGzAAGC9p3zP990A9FgOzXMh0jaDY2+ABxXpsy8B8HhQjNejQ74sJwp9XxgoCQOzCDv2QsiAIorxzxI386IzQDgLjcDmLwt52K8OM42oq9HxY-8M0I2R0XDJCZx4+5FEeIliX+bVP2XCsRLkhSiXrWRfnxbjWLeZ5ZAkaSv2E3CjPudiACkQK4mSoOsuzKKEjSrLE3igPsxj3J-OScTg9FKMMrzcXRYKQoEsL9wI75zPUgLrPi7CnNXOTUvuXp0S6NTtw80jwvQ3pEoK5LiowtKLMK0T9xKrxsty-LL1quTIXkONEJqir33kbM41i2MfgwoaMxK+V0t3OTZHisa3niyaeto8KJPRBNehayCMustaE11eabIYxzltklyfMYk6kpW8j5FkBz-Ju1CqtDTbDoa0MDqm685JKgBWbA-re77NOs-7Aa+07nMq3o-rh4GoZ2mG4b+yHrrO8L4oBoGtpojG4sI7G0fKp78MJ+HccsoqCe+FHida4chkeF0JFkND7ghWRQRIpmWbZ+5iW+VSeeZkt+c50EBaFvKRb59mPXrR59NlsX2eRCFfjLRGu0+D58Tl7K9PxYkfm5kG7A+PWDZymXzfkXX9dVvlIXREiHYN51vntSnCuRWxflN+4PxIv2A++SWmWdflSxDoZ-cDj0IWdWP4-D7LGSGb4U7DyWPSGS0vezhPFPxD5Xbt0PA9Mhs7fuCRHnZgBFHEhg+LX0fzev2ZMyEhl+Ziu5dWVTIHhv7g+b5vkeLPa8Hk3vl7yE0NH9n8+dIVtevQf5An3pHk+FfpQ+XocWX2ex66L3fh9gL8XnVn2dL8vN80u+Dd+afvhxV5uLfp3K-Dr-e+-NL44lsHlM2L9cJ-wftKOOzx96zXpttbQHxsy9CGGfF+HwsTfEUA+L4oJwT5zATfdohDwREjlHdEEBDZDOiJOqZ4CDvjtxJrkL4aFZD5zoRICWz8O7uGPlzZOINhGgkULYLBgjUEn1sAI9hHgPgB0hNfXUkCZFaGUSpMEBCP6QkhLNaeEC9GKUhEnUhGjFFCP0eYj4nw2EM3IUyLm9dlZiKZOArm4IISNwIaCR4+CPHN0eI4lBWiPgvjjmEvGSio44hjmI50GDpHWNQf8feXQ8ScwBAQxkeC8kSE+H4sR+dnhT0IvY2weSC41LujXbBTM8n+zMc09WBD64vAIYoZ0IIyEcMUBIfOBkxGSLQrYIYAAtfpSjFAJK1Bkx6HDDGIi6I8R49cl4EM9F0AJpJtltwhA4g5WS7F6X+Ns3pyDYlCJ0jiZ01SxFEiZPIbZjwoQxKphPKe3xx6PFEVDAAvrcZAegDBGBMGYCwVhQBSDkPIR4wgWCuA0mQaAAB3AwABrcwAB+dA0hoDQBQBQMgwk0XoooJgSA+LQCEuJcgUlwkACeWAmCxD4BQWAmBaX0pJWS1F0B2Wcu5byol-LyXQCwNgMVDKmUaWkFS5AtLMBMB4CYAYwlfBDEgPoQwKq1UauEpYDgvgeDMtpaS5lwlSjqtJUwA16qyCao0pS6l8AeCIEdUa24wL3Cgr1RCpY0LxCwpsPIXQZgyDcrDfC+wjhnAorhIgGQFBigACtMDKHYOgAARLAYgfBTW5tAAAH1ALmzFPAcU8BLeW3NwrGXctzT6P12gA3guMMGk11h4XEh4BQYQwhzCRuQNGzAsaFCIpYDEOFdgHBOBcG4doc75ABCqKu31uBcDAvYFwXg-AODQDIKqydSgVAoHQKu7Nqg6Crv7YO4dIoO2GFAAAXjPTelANwCDgBIOQKgNATDsB0MwVgxBdWdtXaAQgPBoCQArXQYAFAW2gAIFSzA4R+DsuIBO3DoBoAetACmxVxQ6CZtADABAKBcBHpPUYEjab31nrveG9dmQ0NgBNWa5lMH4BkFNcQY9MQq1YtYKuugnRfD5ACHGGI2YUgcYIKqhNLhYPweMJBwwInsWsEY2RqTfhAhydAAppTYAVOLpg3BhDJgVMCeQDp6trBcAQcDaAJgzLh2uDPfGxds7w3TswAF+FtAJ2rpGPZ0NgLrMadzUhlD5nNPuc8950TLn0PRuMEYdLoB0XEHZXSoVsRQC-FsrYWgWX7GKAAIQefNaADgsRSUDA1RAKjqh0DSo89AdrF6aBHsgDAMgFHSWwFAMUZw-BijmEwBQXAQA)

**Comment by Yahweasel** [comment] 2024-10-25 10:52
Yoooooo, you've cracked the code! I'll see how easy it is to adapt the types file later today.

**Comment by Yahweasel** [comment] 2024-10-25 20:45
Please reopen if this doesn't work as expected. I believe this covers *all* cases.

**Closed** 2024-10-25 20:44 UTC

**Comment by longnguyen2004** [comment] 2024-10-26 02:05
Can you release a new version for this change then? Or at least an estimate of when it will come?

**Comment by Yahweasel** [comment] 2024-10-26 03:35
Either Sunday or Monday probably.

I also need a recent fix for some of my own code :rofl:
